---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: grafana
  namespace: monitoring
  annotations:
    fluxcd.io/automated: "false"
    fluxcd.io/tag.chart-image: semver:~4.0
spec:
  releaseName: grafana
  chart:
    repository: https://kubernetes-charts.storage.googleapis.com
    name: grafana
    version: 5.0.23
    paths: stable/
  values:
    rbac:
      create: false

    serviceAccount:
      create: false
    securityContext:
      runAsUser: 472
      runAsGroup: 472
      fsGroup: 472



    downloadDashboardsImage:
      repository: curlimages/curl
      tag: 7.68.0
      pullPolicy: IfNotPresent

    downloadDashboards:
      env: {}
      resources: {}

    ## Pod Annotations
    # podAnnotations: {}

    ## Pod Labels
    # podLabels: {}

    ingress:
      enabled: true
      path: /
      hosts:
        - grafana.minikube.local
      ## Extra paths to prepend to every host configuration. This is useful when working with annotation based services.

    persistence:
      type: pvc
      enabled: false
      # storageClassName: default
      accessModes:
        - ReadWriteOnce
      size: 5Gi
      # annotations: {}
      finalizers:
        - kubernetes.io/pvc-protection

    # Administrator credentials when not using an existing secret (see below)
    adminUser: admin
    adminPassword: admin


    plugins: []
    # - digrich-bubblechart-panel
    # - grafana-clock-panel

    ## Configure grafana datasources
    ## ref: http://docs.grafana.org/administration/provisioning/#datasources
    ##
