---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: influxdb
  namespace: monitoring
  annotations:
    fluxcd.io/automated: "false"
    fluxcd.io/tag.chart-image: semver:~4.0
spec:
  releaseName: influxdb
  chart:
    repository: https://helm.influxdata.com/
    name: influxdb
    version: 4.8.2
    paths: influxdata/
  values:
    config:
      reporting_disabled: false
    ingress:
      enabled: true
      hostname: influxdb.minikube.local
    env:
      - name: INFLUXDB_DB
        value: "minikube"

    setDefaultUser:
      enabled: true
      user:

        ## The user name
        ## Default: "admin"
        username: "minikube"

        ## User password
        ## single quotes must be escaped (\')
        ## Default: (Randomly generated 10 characters of AlphaNum)
        password: 'minikube'

        ## The user name and password are obtained from an existing secret. The expected
        ## keys are `influxdb-user` and `influxdb-password`.
        ## If set, the username and password values above are ignored.
        # existingSecret: influxdb-auth

        ## User privileges
        ## Default: "WITH ALL PRIVILEGES"
        privileges: "WITH ALL PRIVILEGES"
    initScripts:
      enabled: false
      scripts:
        init.iql: |+
          CREATE DATABASE "minikube" WITH DURATION 30d REPLICATION 1 NAME "rp_30d"